# Token generated by Fio Bank
FIO_TOKEN = ""

USEMAIL = False
FROM = ""
TO = [""]
LOCALE = "czech" #For currency formatting
ACCOUNT_NAME = "" #Identifier for account used in email

SMTP_SERVER = ""
SMTP_PORT = 0
SMTP_USER = ""
SMTP_PASSWORD = ""
SMTP_SSL = True
SMTP_TTL = False

USEBULKGATE = False
BULKGATE_ID = ""
BULKGATE_TOKEN = ""
BULKGATE_SENDER = ""
BULKGATE_TO = [""]
