# Token generated by Fio Bank
FIO_TOKEN = ''

FROM = ''
TO = ['']
LOCALE = 'czech' #For currency formatting

SMTP_SERVER = ''
SMTP_PORT = 0
SMTP_USER = ''
SMTP_PASSWORD = ''
SMTP_SSL = True
SMTP_TLS = False