# Token generated by Fio Bank
FIO_TOKEN = ''

FROM = ''
TO = ['']
LOCALE = 'czech' #For currency formatting
ACCOUNT_NAME = '' #Identifier for account used in email

SMTP_SERVER = ''
SMTP_PORT = 0
SMTP_USER = ''
SMTP_PASSWORD = ''
SMTP_SSL = True
SMTP_TTL = False