# Token generated by Fio Bank
FIO_TOKEN = ''

FROM = ''
TO = ['']
LOCALE = '' #For currency formatting eg. czech

# Please note that I am using TLS connection. See mail.py if you need to adjust email server connection
SMTP_SERVER = ''
SMTP_PORT = 0
SMTP_USER = ''
SMTP_PASSWORD = ''